#pragma once

/*	
*	code in this file was generated by python-script 
*										 ©Y.Nikolaev 
*								    Date: 27.08.2021
*/

		{5.48, 6.48, 0.0, WITHOUT_C, REAL, TWO_ROOTS, 0, -1.18248, 0, 0},
		{ 1.0 ,  0.0,  0.0,   WITHOUT_B_C,         REAL,		  ONE_ROOT,        0,    EMPTY_X, 0, 0 },
		{ 48.8, 58.2,  1.0,          FULL,         REAL,		 TWO_ROOTS, -1.17519, -0.0174371, 0, 0 },
		{ -7.0, 49.0,  1.0,          FULL,         REAL,		 TWO_ROOTS, -0.020349,    7.0203, 0, 0 },
		{ 0.0, 49.0,  1.0,     WITHOUT_A,		  REAL,		  ONE_ROOT, -0.020408,   EMPTY_X, 0, 0 },
		{ 0.0, 49.0,  0.0,   WITHOUT_A_C,         REAL,		  ONE_ROOT,       0.0,   EMPTY_X, 0, 0 },
		{ 1.0,  0.0, -9.0,     WITHOUT_B,         REAL,		 TWO_ROOTS,       3.0,      -3.0, 0, 0 },
		{ 1.0,  0.0,  9.0,     WITHOUT_B,      COMPLEX,		  TWO_COMP, COMPLEX_X, COMPLEX_X, 0, 3 },
		{ 0.0,  0.0,  0.0,   WITHOUT_ALL,		  REAL,		  ONE_ROOT,  INFINITY,   EMPTY_X, 0, 0 },
		{ 0.0,  0.0,  9.0, NO_ROOTS_TYPE,  NO_ROOTS_IS,		NO_ROOTS_R,   EMPTY_X,   EMPTY_X, 0, 0 },
		{ -39,	-40,   20,			FULL,		  REAL, TWO_ROOTS, -1.393618669, 0.367977643, 0, 0 },
		{ -70,	 12,   54,			FULL,		  REAL, TWO_ROOTS, -0.796768298, 0.968196869, 0, 0 },
		{ -49,	 59,  -17,			FULL,		  REAL, TWO_ROOTS, 0.477484126, 0.726597506, 0, 0 },
		{ -54,	-41,   71,			FULL,	      REAL, TWO_ROOTS, -1.587492813, 0.828233554, 0, 0 },
		{ 63,	-36,  -44,			FULL,		  REAL, TWO_ROOTS, -0.597487476, 1.168916047, 0, 0 },
		{ -11,	-80,  -37,			FULL,		  REAL, TWO_ROOTS, -6.776348371, -0.496378902, 0, 0 },
		{ 52,	 51,   -3,			FULL,		  REAL, TWO_ROOTS, -1.036433495, 0.055664264, 0, 0 },
		{ -72,	 19,   42,			FULL,		  REAL, TWO_ROOTS, -0.643131468, 0.907020357, 0, 0 },
		{ -20,	-51,   16,			FULL,		  REAL, TWO_ROOTS, -2.832441813, 0.282441813, 0, 0 },
		{ -67, 	 17,   43,			FULL,		  REAL, TWO_ROOTS, -0.684236013, 0.937967357, 0, 0 },
		{ 30,	 38,  -58,			FULL,		  REAL, TWO_ROOTS, -2.161222218, 0.894555552, 0, 0 },
		{ 0,		 71,  -23,	   WITHOUT_A,		  REAL, ONE_ROOT, 0.323943662, EMPTY_X, 0, 0 },
		{ -36,	-38,   22,			FULL,		  REAL, TWO_ROOTS, -1.470995936, 0.41544038, 0, 0 },
		{ -79,	 -4,   26,			FULL,		  REAL, TWO_ROOTS, -0.599559302, 0.548926391, 0, 0 },
		{ -36,	-38,   22,			FULL,		  REAL, TWO_ROOTS, -1.470995936, 0.41544038, 0, 0 },
		{40, 72, -52, FULL, REAL, TWO_ROOTS, -2.35258, 0.55259, 0, 0},
		{38, -47, 10, FULL, REAL, TWO_ROOTS, 0.27305, 0.96381, 0, 0},
		{-36, 9, 12, FULL, REAL, TWO_ROOTS, -0.46572, 0.71573, 0, 0},
		{-63, -26, 3, FULL, REAL, TWO_ROOTS, -0.50668, 0.09399, 0, 0},
		{-31, -46, 68, FULL, REAL, TWO_ROOTS, -2.39844, 0.91458, 0, 0},
		{-75, -5, 68, FULL, REAL, TWO_ROOTS, -0.9861, 0.91945, 0, 0},
